// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.33.4
// source: gno/auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Any } from "../google/protobuf/any.js";

export const protobufPackage = "gno.auth";

/** MsgCreateSession creates a new account session. */
export interface MsgCreateSession {
  /** the bech32 address of the session creator */
  creator: string;
  /** the session public key wrapped as a TM2 pubkey Any */
  session_key?:
    | Any
    | undefined;
  /** unix timestamp expiry, or 0 for no expiry */
  expires_at: bigint;
  /** allowed realm paths, or empty for unrestricted paths */
  allow_paths: string[];
  /** spending limit as a std.Coins string, or empty for no spending */
  spend_limit: string;
  /** spending period in seconds, or 0 for lifetime cap */
  spend_period: bigint;
}

/** MsgRevokeSession revokes an existing account session. */
export interface MsgRevokeSession {
  /** the bech32 address of the session creator */
  creator: string;
  /** the session public key wrapped as a TM2 pubkey Any */
  session_key?: Any | undefined;
}

/** MsgRevokeAllSessions revokes all sessions for the creator. */
export interface MsgRevokeAllSessions {
  /** the bech32 address of the session creator */
  creator: string;
}

function createBaseMsgCreateSession(): MsgCreateSession {
  return { creator: "", session_key: undefined, expires_at: 0n, allow_paths: [], spend_limit: "", spend_period: 0n };
}

export const MsgCreateSession: MessageFns<MsgCreateSession> = {
  encode(message: MsgCreateSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.session_key !== undefined) {
      Any.encode(message.session_key, writer.uint32(18).fork()).join();
    }
    if (message.expires_at !== 0n) {
      if (BigInt.asIntN(64, message.expires_at) !== message.expires_at) {
        throw new globalThis.Error("value provided for field message.expires_at of type sint64 too large");
      }
      writer.uint32(24).sint64(message.expires_at);
    }
    for (const v of message.allow_paths) {
      writer.uint32(34).string(v!);
    }
    if (message.spend_limit !== "") {
      writer.uint32(42).string(message.spend_limit);
    }
    if (message.spend_period !== 0n) {
      if (BigInt.asIntN(64, message.spend_period) !== message.spend_period) {
        throw new globalThis.Error("value provided for field message.spend_period of type sint64 too large");
      }
      writer.uint32(48).sint64(message.spend_period);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.session_key = Any.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expires_at = reader.sint64() as bigint;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.allow_paths.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.spend_limit = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.spend_period = reader.sint64() as bigint;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateSession {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      session_key: isSet(object.session_key) ? Any.fromJSON(object.session_key) : undefined,
      expires_at: isSet(object.expires_at) ? BigInt(object.expires_at) : 0n,
      allow_paths: globalThis.Array.isArray(object?.allow_paths)
        ? object.allow_paths.map((e: any) => globalThis.String(e))
        : [],
      spend_limit: isSet(object.spend_limit) ? globalThis.String(object.spend_limit) : "",
      spend_period: isSet(object.spend_period) ? BigInt(object.spend_period) : 0n,
    };
  },

  toJSON(message: MsgCreateSession): unknown {
    const obj: any = {};
    if (message.creator !== undefined) {
      obj.creator = message.creator;
    }
    if (message.session_key !== undefined) {
      obj.session_key = Any.toJSON(message.session_key);
    }
    if (message.expires_at !== undefined) {
      obj.expires_at = message.expires_at.toString();
    }
    if (message.allow_paths?.length) {
      obj.allow_paths = message.allow_paths;
    }
    if (message.spend_limit !== undefined) {
      obj.spend_limit = message.spend_limit;
    }
    if (message.spend_period !== undefined) {
      obj.spend_period = message.spend_period.toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateSession>, I>>(base?: I): MsgCreateSession {
    return MsgCreateSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateSession>, I>>(object: I): MsgCreateSession {
    const message = createBaseMsgCreateSession();
    message.creator = object.creator ?? "";
    message.session_key = (object.session_key !== undefined && object.session_key !== null)
      ? Any.fromPartial(object.session_key)
      : undefined;
    message.expires_at = object.expires_at ?? 0n;
    message.allow_paths = object.allow_paths?.map((e) => e) || [];
    message.spend_limit = object.spend_limit ?? "";
    message.spend_period = object.spend_period ?? 0n;
    return message;
  },
};

function createBaseMsgRevokeSession(): MsgRevokeSession {
  return { creator: "", session_key: undefined };
}

export const MsgRevokeSession: MessageFns<MsgRevokeSession> = {
  encode(message: MsgRevokeSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.session_key !== undefined) {
      Any.encode(message.session_key, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRevokeSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRevokeSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.session_key = Any.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRevokeSession {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      session_key: isSet(object.session_key) ? Any.fromJSON(object.session_key) : undefined,
    };
  },

  toJSON(message: MsgRevokeSession): unknown {
    const obj: any = {};
    if (message.creator !== undefined) {
      obj.creator = message.creator;
    }
    if (message.session_key !== undefined) {
      obj.session_key = Any.toJSON(message.session_key);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRevokeSession>, I>>(base?: I): MsgRevokeSession {
    return MsgRevokeSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRevokeSession>, I>>(object: I): MsgRevokeSession {
    const message = createBaseMsgRevokeSession();
    message.creator = object.creator ?? "";
    message.session_key = (object.session_key !== undefined && object.session_key !== null)
      ? Any.fromPartial(object.session_key)
      : undefined;
    return message;
  },
};

function createBaseMsgRevokeAllSessions(): MsgRevokeAllSessions {
  return { creator: "" };
}

export const MsgRevokeAllSessions: MessageFns<MsgRevokeAllSessions> = {
  encode(message: MsgRevokeAllSessions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRevokeAllSessions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRevokeAllSessions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRevokeAllSessions {
    return { creator: isSet(object.creator) ? globalThis.String(object.creator) : "" };
  },

  toJSON(message: MsgRevokeAllSessions): unknown {
    const obj: any = {};
    if (message.creator !== undefined) {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRevokeAllSessions>, I>>(base?: I): MsgRevokeAllSessions {
    return MsgRevokeAllSessions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRevokeAllSessions>, I>>(object: I): MsgRevokeAllSessions {
    const message = createBaseMsgRevokeAllSessions();
    message.creator = object.creator ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
