#!/bin/bash

PROTO_PATH=./proto
OUT_DIR=./src/proto
PRETTIER=./node_modules/.bin/prettier

FILES=$(find proto -type f -name "*.proto")

mkdir -p ${OUT_DIR}

# Drop the previously generated files so a removed proto does not leave one
# behind. Only files carrying the generator's banner go: index.ts next to them
# is hand-written.
find ${OUT_DIR} -name "*.ts" | while read -r generated; do
  if head -1 "${generated}" | grep -q "Code generated by protoc-gen-ts_proto"; then
    rm "${generated}"
  fi
done

echo "Generating TypeScript files from proto definitions..."
for x in ${FILES}; do
  protoc \
    --plugin="./node_modules/.bin/protoc-gen-ts_proto" \
    --ts_proto_out="${OUT_DIR}" \
    --proto_path="${PROTO_PATH}" \
    --ts_proto_opt="importSuffix=.js,esModuleInterop=true,forceLong=bigint,useOptionals=messages,useDate=false,snakeToCamel=false,emitDefaultValues=json-methods,protoJsonFormat=false" \
    ${x}
done
